### ISSUE TITLE
'cargo clippy' build error

### ISSUE THREAD

**Issue by taprinz** [ccc-spdm-tools/spdm-rs#11]
After following the setup directions, I see the following error when running ```cargo clippy```:

```
error: &-masking with zero
    --> spdmlib/src/common/mod.rs:1466:1
     |
1466 | / bitflags! {
1467 | |     #[derive(Default)]
1468 | |     pub struct SpdmMeasurementContentChanged: u8 {
1469 | |         const NOT_SUPPORTED = 0b0000_0000;
...    |
1472 | |     }
1473 | | }
     | |_^
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bad_bit_mask
     = note: `#[deny(clippy::bad_bit_mask)]` on by default
     = note: this error originates in the macro `__impl_bitflags` which comes from the expansion of the macro `bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This causes the build to fail. I saw this in a clean instance of Ubuntu running in WSL.

This is resolvable via running ```cargo clippy -- -A clippy::bad_bit_mask```, but wanted to report to see if either this is configuration issue on my end, or a bug present at the top of tree.

**Comment by longlongyang** [comment]
It not a configuration issue, it is just that we don't run clippy that way. There is a script to automate it:
https://github.com/ccc-spdm-tools/spdm-rs/blob/cbdd3bb6791c7eb3c4c3d67c795e038478a2876b/sh_script/build.sh#L30-L44

Developer is expected to run clippy by `./sh_script/build.sh -c`

**Comment by jyao1** [comment]
@longlongyang , thanks. But I expect we should fix it some day.

User should be able to run it manually.

**Comment by longlongyang** [comment]
> @longlongyang , thanks. But I expect we should fix it some day.
> 
> User should be able to run it manually.

yeah, agree

**Comment by taprinz** [comment]
Yeah, I was just going off the instructions in the readme. We should point users to the build script if that is the main supported path.

**Comment by OuyangHang33** [comment]
Now below comand can pass the clippy build:
`cargo clippy -- -D warnings  -A clippy::bad_bit_mask -A clippy::derivable_impls`
I'm going to fix below clippy lints:
` -A clippy::bad_bit_mask -A clippy::derivable_impls`
