### ISSUE TITLE
Increase MAX_SPDM_VERSION_COUNT to support more versions in VERSION response

### ISSUE THREAD

**Issue by xiaoyuxlu** [ccc-spdm-tools/spdm-rs#127]
There are 4 SPDM versions. It may failed if responder return 4 versions in VERSION response.

https://github.com/ccc-spdm-tools/spdm-rs/blob/58042adf899f28b6cce666f7466d348c58231808/spdmlib/src/protocol/version.rs#L63

**Comment by jyao1** [comment]
Yes, we need to support to talk to SPDM peer which may have SPDM 1.3
