### ISSUE TITLE
Should also check the len is bigger than the length + length count

### ISSUE THREAD

**Issue by longlongyang** [ccc-spdm-tools/spdm-rs#15]
https://github.com/ccc-spdm-tools/spdm-rs/blob/cb06559c33c27231bad686e9a854ffc97710b50a/spdmlib/src/crypto/x509v3.rs#L230-L248

**Comment by xiaoyuxlu** [comment]
After fixing, please remove `ignore` in the tests

**Comment by jyao1** [comment]
> After fixing, please remove ignore in the tests

Please remove ignore when you fix it.
