### ISSUE TITLE
Need to send update version number in version response.

### ISSUE THREAD

**Issue by IntelCaisui** [ccc-spdm-tools/spdm-rs#157]
SPDM 1.3 has strict regulation that version update shall be sent to requester for information:

![image](https://github.com/user-attachments/assets/7df6463d-d34d-45b4-b1f8-421460a2a6b0)

Latest spdm specification is 1.3.2, so need to update implementation to send out update numbers based on Major and Minor Version rather than send update numbers as 0:

```
        for v in self.common.config_info.spdm_version.iter().flatten() {
            versions[version_number_entry_count] = SpdmVersionStruct::init(*v, 0);
            version_number_entry_count += 1;
        }
```

**Comment by jyao1** [comment]
The patch update is informative. I dont think it is mandatory.
