### ISSUE TITLE
function check_length in x509v3.rs doesn't reject non canonical encoding length

### ISSUE THREAD

**Issue by longlongyang** [ccc-spdm-tools/spdm-rs#28]
For example, 
when the length encoding slice is : 0x81 0x12,
expected behavior: spdm-rs reject it and treat it as invalid length encoding,
current behavior: spdm-rs accept it and treat is as valid length encoding.

For reference: https://github.com/ccc-spdm-tools/spdm-rs/blob/3c678907cd3d121b8b2cc5d5048958b1201a8099/spdmlib/src/crypto/spdm_ring/cert_operation_impl.rs#L86-L135

**Comment by xiaoyuxlu** [comment]
After fixing, please remove "ignore" in the test
