### ISSUE TITLE
Requesting 

### ISSUE THREAD

**Issue by Salkimmich** [ccc-spdm-tools/spdm-rs#40]
Hello SPDM Maintainers:

Once this review is complete, you are welcome to remove these privileges, and alternatively, I can help you to establish these by assisting your administrators with direct implementation.

I'm reaching out to request access to the repository settings for SPDM. Many best practices have already been established within the project, but I am preparing for future updates and enhancements to further strengthen security, compliance, and collaboration efforts.

I would like to run [CLOMonitor](https://clomonitor.io/search?page=1) checks for each repository, but requesting direct access to repository settings so I can run these checks locally without exposing your project to a publicly available dashboard.

To effectively review and enhance the project's security, compliance, and collaboration efforts, I require ownership or administrative privileges within the repository. This level of access will enable me to conduct a thorough review, identify areas for improvement, and propose enhancements that align with the project's objectives. Once this review is complete, you are welcome to remove these privileges, and alternatively, I can help you to establish these by assisting your administrators with direct implementation. 

Granting me access to the repository settings will enable me to review the existing configurations, identify any areas for improvement, and implement additional best practices and other measures to enhance the development workflow and project governance. Best practices can be highly specific to each project's unique setup and requirements, so our approach will be flexible and tailored to accommodate the SPDM's specific needs.

Following review, any proposed changes to the process will be discussed transparently with the project maintainers and contributors. The standard PR and Issue process will be used to ensure full visibility and collaboration on all recommendations.

I look forward to collaborating with you for future updates!

Thanks,
Sal
CCC Technical Community Architect

**Comment by jyao1** [comment]
Invitation is sent.

**Comment by Salkimmich** [comment]
Great, I'm in! I'll get a scan and a review back to you in an GH issue the next 7 days: then I'm happy to have these permissions removed by March 6th, always favor least privelages.

**Comment by Salkimmich** [comment]
Alright perfect, I've run a scan of your security posture and it will be available in a GH Issue on the main repository for review. I recommend removing my maintainer access at this time to ensure best security practice!
