### ISSUE TITLE
need robust way to handle key_update 

### ISSUE THREAD

**Issue by jyao1** [ccc-spdm-tools/spdm-rs#7]
from https://github.com/intel/rust-spdm/issues/27

if key_update message failed, we need rollback to original keys.

**Comment by OuyangHang33** [comment]
| Key_Update_Operation    | Msg Header  | type | Expected Behaviors when fail   |
| ----------  | -----------  |-----------      |-----------| 
|UpdateAllkeys      | KEY_UPDATE_ACK  tag1      | response      |  use old key, if S2 and S3 updated must be rollback    | 
|UpdateSingleKey  | KEY_UPDATE_ACK  tag1      |  response     |  use old key, if S2 updated must be rollback     | 
|VerifyNewKey       |  KEY_UPDATE tag2               |  request       |  keep session working, keys backup should not be cleanup| 
|VerifyNewKey       |  KEY_UPDATE_ACK tag2      |  response     |  keep session working, keys backup should not be cleanup. Sender can retry the request|

**Comment by OuyangHang33** [comment]
### Test UpdateAllKeys operation on SPDM-rs
Key_Update_Operation | type | Expected   Behaviors when fail |  Responder (Rsp) Actual Behaviors | Request (Req) Actual Behaviors
-- | -- | -- | -- | --
UpdateAllkeys | request   (send unknow request) | use old key, rsp should return Err, req must do rollback | send unkonw and update key, then fail and rsp return 12 7f 01 00 | can't   receive err msg. get measure fail
UpdateAllkeys | response   (modify msg used-1) | use old key, rsp no Err, req must do rollback | send rsp no err | rollback old key. get measure fail
VerifyNewKey | request   (send unknow request) | rsp return Err. req get Err and keep session working | rsp return 12 7f 01 00.      get measure success | send req no err, can receive err msg, get measure success
VerifyNewKey | response   (modify msg used-1) | rsp no Err, req keep session working, keys backup should not be cleanup. Sender can retry the request | send rsp no err | return verify fail. Get measure success.

### Test UpdateAllKeys operation on SPDM-EMU(libspmd)
Key_Update_Operation | type | Expected   Behaviors when fail |  Responder (Rsp) Actual Behaviors | Request (Req) Actual Behaviors
-- | -- | -- | -- | --
UpdateAllkeys | request   (send unknow request) | use old key, rsp should return Err, req must do rollback | send   unkonw and update key, then fail and rsp return 12 7f 01 00 | WIP 
UpdateAllkeys | response   (modify msg used-1) |use old key, rsp no Err, req must do rollback | rsp   no err. | WIP
VerifyNewKey | request   (send unknow request) | rsp return Err. req get Err and keep session working | rsp   return 12 7f 01 00.      get measure success | WIP
VerifyNewKey | response   (modify msg used-1) |rsp no Err, req keep session working, keys backup should not be cleanup. Sender can retry the request | rsp no err | WIP

**Comment by OuyangHang33** [comment]
Regards to this scenario: When SPDM-rs Requester create new keys and send wrong KeyUpdate operation, it can't receive Err msg from responder.

Root cause: responder keys between Req and Rsp are dismatched. SPDM-rs only try `receive_message` with current keys, and rollback to backup keys happend after receive Err msg.
https://github.com/ccc-spdm-tools/spdm-rs/blob/003a4982f3f298ca8daa1bdfb79530bfd108e5cb/spdmlib/src/common/session.rs#L897-L916

Libspdm give a good example `libspdm_receive_response` to solve this problem:
https://github.com/DMTF/libspdm/blob/3bbcb24dbae81a25cb04dd185b0fe948e6ac6b25/library/spdm_requester_lib/libspdm_req_send_receive.c#L194-L197
```
 if (status == LIBSPDM_STATUS_SESSION_TRY_DISCARD_KEY_UPDATE) {
        /* Failed to decode, but have backup keys. Try rolling back before aborting.
         * message_session_id must be valid for us to have attempted decryption. */
        if (message_session_id == NULL) {
            return LIBSPDM_STATUS_INVALID_STATE_LOCAL;
        }
        temp_session_context = libspdm_get_secured_message_context_via_session_id(
            context, *message_session_id);
        if (temp_session_context == NULL) {
            return LIBSPDM_STATUS_INVALID_STATE_LOCAL;
        }

        result = libspdm_activate_update_session_data_key(
            temp_session_context, LIBSPDM_KEY_UPDATE_ACTION_RESPONDER, false);
        if (!result) {
            return LIBSPDM_STATUS_INVALID_STATE_LOCAL;
        }

        /* Retry decoding message with backup Requester key.
         * Must reset some of the parameters in case they were modified */
        message_session_id = NULL;
        is_message_app_message = false;
        *response = backup_response;
        *response_size = backup_response_size;
        status = context->transport_decode_message(
            context, &message_session_id, &is_message_app_message,
            false, message_size, message, response_size, response);

        reset_key_update = true;
    }
```

**Comment by OuyangHang33** [comment]
For this scenario: 
| Key_Update_Operation    | Msg Header  | type | Expected Behaviors when fail   |
| ----------  | -----------  |-----------      |-----------|
|UpdateAllkeys      | KEY_UPDATE_ACK  tag1      | response      |  use old key, if S2 and S3 updated, must do rollback. sender keys backup should be keeped | 

### Test scenario: 
After responder receive the correct UpdateAllkeys request and handle the key update operation (Update S2`new` and S3`new`, and write response with S3`new`), the requester get the incomplete message (like origin is `12, 69, 01, 01`, but get `12, 69, 01`), the requester will do rollback keys. 
For requester, S2new and S3new is not activated, S2new and S3new will be rollback to old one.
For responder, S3new is activated, S3 old key has been droped, so only S2new will be rollback to old one.

### Result: 
Requester get old S3 key, and responder get S3 new key, dismatched, other operation will be fail like get_measurement.

### Question:
From spec v1.2.1 p.p.131:
> The sender shall not use the new transmit key until after reception of the KEY_UPDATE_ACK response.
> If the sender has not received KEY_UPDATE_ACK , the sender can retry or end the session. The sender shall not proceed to the next step until successfully receiving the corresponding KEY_UPDATE_ACK .
Does it mean that if retry fail, session should be end when meet above scenario?

**Comment by jyao1** [comment]
I think we only need to consider below failure scenario:
1) An ERROR message that can be decrypted successfully.
2) A garbage message that cannot be decrypted by old key or new key.
3) No message is received.

We don't need to consider the situation that attacker can create an invalid message that can be decrypted successfully. If the attacker has such capability, then there will be no security any more.
