### ISSUE TITLE
need to reset reset_message_m in case of error.

### ISSUE THREAD

**Issue by jyao1** [ccc-spdm-tools/spdm-rs#91]
See the issue in libspdm project - https://github.com/DMTF/libspdm/issues/2114.

**Comment by OuyangHang33** [comment]
Is this issue same as https://github.com/intel/rust-spdm/issues/24 ?

**Comment by jyao1** [comment]
Right.
Does the requester do the same thing on error handling?

**Comment by OuyangHang33** [comment]
Base on below lines, requester will do `reset_message_m `after getting error status from `handle_spdm_measurement_record_response `except `NOT_READY`

https://github.com/ccc-spdm-tools/spdm-rs/blob/ed2729581e900b33ef8609d706faa96546c4f3cb/spdmlib/src/requester/get_measurements_req.rs#L34-L50

**Comment by OuyangHang33** [comment]
This bug was fixed, so close it.
