### ISSUE TITLE
Returning SPDM_STATUS_INVALID_PARAMETER for SpdmErrorRequestResynch regardless of session_id presence.

### ISSUE THREAD

**Issue by xiaoyuxlu** [ccc-spdm-tools/spdm-rs#98]
https://github.com/ccc-spdm-tools/spdm-rs/blob/a2aa7a6adf36b1f4cd3f4911542b1d45a64db38a/spdmlib/src/requester/handle_error_response_req.rs#L27-L36

**Comment by longlongyang** [comment]
This is not a bug. Since spdmlib doesn't support resync now, returning error to call to tell call what happened is an expected behavior. But the error type is not correct, SPDM_STATUS_INVALID_STATE_PEER is more suitable.
